name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: pranavkumar.balakrishnan@gramener.com
        run: echo "Hello, world!"
